CREATE OR REPLACE PACKAGE PKG_TOTAL_PRICE AS
    FUNCTION CALCULATE_TOTAL_PRICE(
        P_BOOKING_ID IN NUMBER
    ) RETURN NUMBER;
END PKG_TOTAL_PRICE;

CREATE OR REPLACE PACKAGE BODY PKG_TOTAL_PRICE AS

    FUNCTION CALCULATE_TOTAL_PRICE(
        P_BOOKING_ID IN NUMBER
    ) RETURN NUMBER IS
        V_ROOM_PRICE     NUMBER;
        V_SERVICES_PRICE NUMBER;
        V_TOTAL_PRICE    NUMBER;
    BEGIN
        SELECT
            TOTAL_PRICE INTO V_ROOM_PRICE
        FROM
            BOOKINGS
        WHERE
            BOOKING_ID = P_BOOKING_ID;
        SELECT
            SUM(SERVICES.PRICE * BOOKING_SERVICES.QUANTITY) INTO V_SERVICES_PRICE
        FROM
            BOOKING_SERVICES
            INNER JOIN SERVICES
            ON BOOKING_SERVICES.SERVICE_ID = SERVICES.SERVICE_ID
        WHERE
            BOOKING_SERVICES.BOOKING_ID = P_BOOKING_ID;
        V_TOTAL_PRICE := V_ROOM_PRICE + V_SERVICES_PRICE;
        RETURN V_TOTAL_PRICE;
    END CALCULATE_TOTAL_PRICE;
END PKG_TOTAL_PRICE;

--Test
SET SERVEROUTPUT ON;

DECLARE
    v_booking_total NUMBER;
BEGIN
    v_booking_total := PKG_TOTAL_PRICE.calculate_total_price(6504);
    DBMS_OUTPUT.PUT_LINE('The total price for the booking is: ' || v_booking_total);
END;

