CREATE OR REPLACE FUNCTION CALCULATE_TOTAL_PRICE(
    P_BOOKING_ID IN NUMBER
) RETURN NUMBER IS
    V_ROOM_PRICE     NUMBER;
    V_SERVICES_PRICE NUMBER;
    V_TOTAL_PRICE    NUMBER;
BEGIN
    SELECT
        TOTAL_PRICE INTO V_ROOM_PRICE
    FROM
        BOOKINGS
    WHERE
        BOOKING_ID = P_BOOKING_ID;

    SELECT
        SUM(SERVICES.PRICE * BOOKING_SERVICES.QUANTITY) 
        INTO V_SERVICES_PRICE
    FROM
        BOOKING_SERVICES
        INNER JOIN SERVICES
        ON Booking_Services.service_id = Services.service_id
    WHERE
        BOOKING_SERVICES.BOOKING_ID = P_BOOKING_ID ;
    V_TOTAL_PRICE := V_ROOM_PRICE + V_SERVICES_PRICE;
    RETURN V_TOTAL_PRICE;
END;

--Test
SET SERVEROUTPUT ON;

DECLARE
    v_booking_total NUMBER;
BEGIN
    v_booking_total := calculate_total_price(6504);
    DBMS_OUTPUT.PUT_LINE('The total price for the booking is: ' || v_booking_total);
END;

