CREATE OR REPLACE PROCEDURE DELETE_BOOKING(
    P_BOOKING_ID NUMBER
) AS
BEGIN
    DELETE FROM BOOKING_SERVICES
    WHERE
        BOOKING_ID = P_BOOKING_ID;
    DELETE FROM BOOKINGS
    WHERE
        BOOKING_ID = P_BOOKING_ID;
    DBMS_OUTPUT.PUT_LINE('Booking deletion successful.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error has occurred while deleting');
END;

CREATE OR REPLACE PROCEDURE ADD_SERVICE(
    P_BOOKING_ID NUMBER,
    P_SERVICE_NAME VARCHAR,
    P_QUANTITY NUMBER DEFAULT 1
)IS
    V_SERVICE_ID NUMBER;
BEGIN
    SELECT
        SERVICE_ID INTO V_SERVICE_ID
    FROM
        SERVICES
    WHERE
        SERVICE_NAME = P_SERVICE_NAME;
    INSERT INTO BOOKING_SERVICES(
        BOOKING_ID,
        SERVICE_ID,
        QUANTITY
    )VALUES(
        P_BOOKING_ID,
        V_SERVICE_ID,
        P_QUANTITY
    );
END;

CREATE OR REPLACE PROCEDURE MODIFY_BOOKING(
    P_BOOKING_ID NUMBER,
    P_NEW_CHECK_IN TIMESTAMP,
    P_NEW_CHECK_OUT TIMESTAMP
)IS
    V_PRICE_PER_NIGHT NUMBER;
    V_ROOM_ID         NUMBER;
    V_NEW_TOTAL_PRICE NUMBER;
BEGIN
    SELECT
        ROOM_ID INTO V_ROOM_ID
    FROM
        BOOKINGS
    WHERE
        BOOKING_ID = P_BOOKING_ID;
    SELECT
        PRICE_PER_NIGHT INTO V_PRICE_PER_NIGHT
    FROM
        ROOMS
    WHERE
        ID = V_ROOM_ID;
    V_NEW_TOTAL_PRICE := V_PRICE_PER_NIGHT * EXTRACT(DAY FROM (P_NEW_CHECK_OUT - P_NEW_CHECK_IN));
    UPDATE BOOKINGS
    SET
        CHECK_IN_DATE = P_NEW_CHECK_IN,
        CHECK_OUT_DATE = P_NEW_CHECK_OUT,
        TOTAL_PRICE = V_NEW_TOTAL_PRICE
    WHERE
        BOOKING_ID = P_BOOKING_ID;
END;
CREATE OR REPLACE PROCEDURE CREATE_BOOKING(
    P_GUEST_NAME VARCHAR,
    P_PHONE_NUMBER VARCHAR,
    P_EMAIL VARCHAR,
    P_ROOM_TYPE VARCHAR,
    P_CHECK_IN_DATE TIMESTAMP,
    P_CHECK_OUT_DATE TIMESTAMP,
    p_service VARCHAR
)is
    V_GUEST_ID             NUMBER;
    V_ROOM_ID              NUMBER;
    V_TOTAL_PRICE          NUMBER;
    V_ROOM_PRICE_PER_NIGHT NUMBER;
    v_booking_id number;
BEGIN
    BEGIN --guest check
        SELECT
            ID INTO V_GUEST_ID
        FROM
            GUESTS
        WHERE
            EMAIL = P_EMAIL;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            V_GUEST_ID := CREATE_GUESTS(
                P_GUEST_NAME => P_GUEST_NAME,
                P_PHONE_NUMBER => P_PHONE_NUMBER,
                P_EMAIL => P_EMAIL
            );
    END;

    BEGIN --room check
        SELECT
            ID,
            PRICE_PER_NIGHT 
            INTO V_ROOM_ID, V_ROOM_PRICE_PER_NIGHT
        FROM
            ROOMS
        WHERE
            ROOM_TYPE = P_ROOM_TYPE
            AND IS_AVAILABLE = 'Y';
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('The selected room is not available');
            RETURN;
    END;

    BEGIN
        V_TOTAL_PRICE := V_ROOM_PRICE_PER_NIGHT * EXTRACT(DAY FROM (P_CHECK_OUT_DATE - P_CHECK_IN_DATE));
        INSERT INTO BOOKINGS (
            GUEST_ID,
            ROOM_ID,
            CHECK_IN_DATE,
            CHECK_OUT_DATE,
            TOTAL_PRICE
        ) VALUES (
            V_GUEST_ID,
            V_ROOM_ID,
            P_CHECK_IN_DATE,
            P_CHECK_OUT_DATE,
            V_TOTAL_PRICE
        ) RETURNING BOOKING_ID INTO V_BOOKING_ID;
    END;

    BEGIN
        ADD_SERVICE(
            P_BOOKING_ID => V_BOOKING_ID,
            P_SERVICE_NAME => P_SERVICE
        );
    END;
END;

SET SERVEROUTPUT ON;
BEGIN
    CREATE_BOOKING(
        P_GUEST_NAME => 'Akssss Lab',
        P_PHONE_NUMBER => '1234567890',
        P_EMAIL => 'akos.valami@example.com',
        P_ROOM_TYPE => 'Double',
        P_CHECK_IN_DATE => TO_TIMESTAMP('2024-12-20 14:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        P_CHECK_OUT_DATE => TO_TIMESTAMP('2024-12-22 10:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        p_service => 'Breakfast'
    );
END;
BEGIN
    ADD_SERVICE(
        P_BOOKING_ID => 6503,
        P_SERVICE_NAME => 'Breakfast'
    );
END;
BEGIN
    DELETE_BOOKING(
        P_BOOKING_ID => 6503
    );
END;
BEGIN
    MODIFY_BOOKING(
        P_BOOKING_ID       => 6502,
        P_NEW_CHECK_IN     => TO_TIMESTAMP('2024-12-20 15:00:00', 'YYYY-MM-DD HH24:MI:SS'),
        P_NEW_CHECK_OUT    => TO_TIMESTAMP('2024-12-23 10:00:00', 'YYYY-MM-DD HH24:MI:SS')
    );
end;

