CREATE OR REPLACE PACKAGE PKG_ROOM_AVAILABILITY AS

    PROCEDURE UPDATE_ROOM_AVAILABILITY(
        P_ROOM_ID IN NUMBER
    );

    PROCEDURE RESTORE_ROOM_AVAILABILITY(
        P_ROOM_ID IN NUMBER
    );
END PKG_ROOM_AVAILABILITY;

CREATE OR REPLACE PACKAGE BODY PKG_ROOM_AVAILABILITY AS

    PROCEDURE RESTORE_ROOM_AVAILABILITY(
        P_ROOM_ID IN NUMBER
    ) AS
    BEGIN
        UPDATE ROOMS
        SET
            IS_AVAILABLE = 'Y'
        WHERE
            ID = P_ROOM_ID;
    END RESTORE_ROOM_AVAILABILITY;

    PROCEDURE UPDATE_ROOM_AVAILABILITY(
        P_ROOM_ID IN NUMBER
    ) AS
    BEGIN
        UPDATE ROOMS
        SET
            IS_AVAILABLE = 'N'
        WHERE
            ID = P_ROOM_ID;
    END UPDATE_ROOM_AVAILABILITY;
END PKG_ROOM_AVAILABILITY;