CREATE TABLE GUESTS(
    QUEST_ID NUMBER PRIMARY KEY,
    QUEST_NAME VARCHAR(250) NOT NULL,
    PHONE_NUMBER VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL
);

CREATE TABLE ROOMS(
    ROOM_ID NUMBER PRIMARY KEY,
    ROOM_TYPE VARCHAR(20) NOT NULL,
    PRICE_PER_NIGHT NUMBER NOT NULL,
    IS_AVAILABLE VARCHAR(1) default 'Y' check(is_available in ( 'Y', 'N' ) )
);

CREATE TABLE BOOKINGS(
    BOOKING_ID NUMBER PRIMARY KEY,
    QUEST_ID NUMBER NOT NULL CONSTRAINT QUEST_FK REFERENCES GUESTS(QUEST_ID),
    ROOM_ID NUMBER NOT NULL CONSTRAINT ROOM_FK REFERENCES ROOMS(ROOM_ID),
    CHECK_IN_DATE TIMESTAMP(6) NOT NULL,
    CHECK_OUT_DATE TIMESTAMP(6) NOT NULL,
    TOTAL_PRICE NUMBER NOT NULL
);

CREATE TABLE SERVICES(
    SERVICE_ID NUMBER PRIMARY KEY,
    SERVICE_NAME VARCHAR(20) NOT NULL,
    PRICE NUMBER NOT NULL
);

CREATE TABLE BOOKIGN_SERVICES(
    BOOKING_SERVICE_ID NUMBER PRIMARY KEY,
    BOOKING_ID NUMBER NOT NULL CONSTRAINT BOOKING_FK REFERENCES BOOKINGS(BOOKING_ID),
    SERVICE_ID NUMBER NOT NULL CONSTRAINT SERVICE_FK REFERENCES SERVICES(SERVICE_ID),
    QUANTITY NUMBER
);