CREATE SEQUENCE GUEST_ID_SEQ START WITH 2340;

CREATE SEQUENCE ROOM_ID_SEQ START WITH 1500;

CREATE SEQUENCE BOOKING_ID_SEQ START WITH 6500;

CREATE SEQUENCE SERVICE_ID_SEQ START WITH 7500;

CREATE SEQUENCE booking_SERVICE_ID_SEQ START WITH 8000;

CREATE OR REPLACE TRIGGER QUEST_SEQ_TRG BEFORE
    INSERT ON GUESTS FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := GUEST_ID_SEQ.NEXTVAL;
    END IF;
END;


CREATE OR REPLACE TRIGGER ROOMS_SEQ_TRG BEFORE
    INSERT ON ROOMS FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := ROOM_ID_SEQ.NEXTVAL;
    END IF;
END;

CREATE OR REPLACE TRIGGER BOOKINGS_SEQ_TRG BEFORE
    INSERT ON BOOKINGS FOR EACH ROW
BEGIN
    IF :NEW.BOOKING_ID IS NULL THEN
        :NEW.BOOKING_ID := BOOKING_ID_SEQ.NEXTVAL;
    END IF;
END;

CREATE OR REPLACE TRIGGER SERVICE_SEQ_TRG BEFORE
    INSERT ON SERVICES FOR EACH ROW
BEGIN
    IF :NEW.SERVICE_ID IS NULL THEN
        :NEW.SERVICE_ID := SERVICE_ID_SEQ.NEXTVAL;
    END IF;
END;

CREATE OR REPLACE TRIGGER BOOKING_SERVICE_SEQ_TRG BEFORE
    INSERT ON BOOKING_SERVICES FOR EACH ROW
BEGIN
    IF :NEW.BOOKING_SERVICE_ID IS NULL THEN
        :NEW.BOOKING_SERVICE_ID := BOOKING_SERVICE_ID_SEQ.NEXTVAL;
    END IF;
END;

CREATE OR REPLACE TRIGGER update_room_availability
AFTER INSERT ON Bookings
FOR EACH ROW
BEGIN
    UPDATE Rooms
    SET is_available = 'N'
    WHERE id = :NEW.room_id;
END;

CREATE OR REPLACE TRIGGER restore_room_availability
AFTER DELETE ON Bookings
FOR EACH ROW
BEGIN
    UPDATE Rooms
    SET is_available = 'Y'
    WHERE id = :OLD.room_id;
END;

drop trigger update_room_availability;
drop TRIGGER restore_room_availability;